application: meenakshi-ocr
version: 1
runtime: python27
api_version: 1
threadsafe: yes


handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /public
  static_dir: public
  
- url: /jquery
  static_dir: static/jquery 
  
- url: /img
  static_dir: static/img 
  
- url: /misc
  static_dir: static/misc 
  
- url: /static
  static_dir: static
  
- url: /
  script: main.app
  
- url: /reviews
  script: main.app
  
- url: /dev
  script: main.app
  
- url: /demo
  script: main.app

- url: /.*
  static_files: static/misc/404.html
  upload: static/misc/404.html

libraries:
- name: webapp2
  version: "2.5.2"
  
- name: jinja2
  version: "2.6"
